### ISSUE TITLE
npm run build throws -angular2-jwt/angular2-jwt"' has no exported member 'AUTH_PROVIDERS'.

### ISSUE THREAD

**Issue by greenstevester** [ddellamico/ionic-conference-app#1]
Hi There,

Great work on pimping up the original ionic2-conference-app, very impressed with your RxJs mods !!
"npm run dev" worked fine, but "npm run build" threw a jwt exception:

10:22:00]  ngc: Error: Error at /Users/XXX/javasource/ionic/ionicV2/ddellamico-ionic-conference-app/.tmp/app/app.module.ngfactory.ts:248:33: Module '"/Users/XXX/javasource/ionic/ionicV2/ddellamico-ionic-conference-app/node_modules/angular2-jwt/angular2-jwt"' has no exported member 'AUTH_PROVIDERS'.
Error at /Users/XXX/javasource/ionic/ionicV2/ddellamico-ionic-conference-app/.tmp/app/app.module.ngfactory.ts:509:38: Module '"/Users/XXX/javasource/ionic/ionicV2/ddellamico-ionic-conference-app/node_modules/angular2-jwt/angular2-jwt"' has no exported member 'AUTH_PROVIDERS'.

It was reported here also:https://forum.ionicframework.com/t/angular2-jwt-after-rc0-broken/65043

I removed AUTH_PROVIDERS from app.module.ts and it worked fine.

Cheers,
Steve

**Comment by ddellamico** [comment]
Hello Steve !

Many thanks for your suggestion, I removed 'AUTH_PROVIDERS' and all works like charm now !
When I think how many hours I spent to find out a fix to this problem ! :)

Cheers,

Damien

**Comment by greenstevester** [comment]
Hi Damien,

No worries, glad I could help - it took me a while reading through the forums threads but eventually found what worked. As I said you really have done some great work here as it's given me a crash course in both RxJs and RX Store.  I am still not quite sure about ngrx/effects...and how it helps as opposed to not having it (probably my current lack of understanding).

Cheers,
Steve
